/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PaymentLinkService } from "../paymentLink.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PaymentLinkCreateInput } from "./PaymentLinkCreateInput";
import { PaymentLink } from "./PaymentLink";
import { PaymentLinkFindManyArgs } from "./PaymentLinkFindManyArgs";
import { PaymentLinkWhereUniqueInput } from "./PaymentLinkWhereUniqueInput";
import { PaymentLinkUpdateInput } from "./PaymentLinkUpdateInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PaymentLinkControllerBase {
  constructor(
    protected readonly service: PaymentLinkService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PaymentLink })
  @nestAccessControl.UseRoles({
    resource: "PaymentLink",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPaymentLink(
    @common.Body() data: PaymentLinkCreateInput
  ): Promise<PaymentLink> {
    return await this.service.createPaymentLink({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        linkId: true,
        requestedAmountInCrypto: true,
        requestedAmountInFiat: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PaymentLink] })
  @ApiNestedQuery(PaymentLinkFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PaymentLink",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paymentLinks(@common.Req() request: Request): Promise<PaymentLink[]> {
    const args = plainToClass(PaymentLinkFindManyArgs, request.query);
    return this.service.paymentLinks({
      ...args,
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        linkId: true,
        requestedAmountInCrypto: true,
        requestedAmountInFiat: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PaymentLink })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentLink",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paymentLink(
    @common.Param() params: PaymentLinkWhereUniqueInput
  ): Promise<PaymentLink | null> {
    const result = await this.service.paymentLink({
      where: params,
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        linkId: true,
        requestedAmountInCrypto: true,
        requestedAmountInFiat: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PaymentLink })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentLink",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePaymentLink(
    @common.Param() params: PaymentLinkWhereUniqueInput,
    @common.Body() data: PaymentLinkUpdateInput
  ): Promise<PaymentLink | null> {
    try {
      return await this.service.updatePaymentLink({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          expiresAt: true,
          id: true,
          linkId: true,
          requestedAmountInCrypto: true,
          requestedAmountInFiat: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PaymentLink })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentLink",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePaymentLink(
    @common.Param() params: PaymentLinkWhereUniqueInput
  ): Promise<PaymentLink | null> {
    try {
      return await this.service.deletePaymentLink({
        where: params,
        select: {
          createdAt: true,
          expiresAt: true,
          id: true,
          linkId: true,
          requestedAmountInCrypto: true,
          requestedAmountInFiat: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Transaction",
    action: "read",
    possession: "any",
  })
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: PaymentLinkWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        paidAmountInCrypto: true,
        paidAmountInFiat: true,

        paymentLink: {
          select: {
            id: true,
          },
        },

        paymentMethod: true,
        status: true,
        transactionId: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  @nestAccessControl.UseRoles({
    resource: "PaymentLink",
    action: "update",
    possession: "any",
  })
  async connectTransactions(
    @common.Param() params: PaymentLinkWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updatePaymentLink({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  @nestAccessControl.UseRoles({
    resource: "PaymentLink",
    action: "update",
    possession: "any",
  })
  async updateTransactions(
    @common.Param() params: PaymentLinkWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updatePaymentLink({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  @nestAccessControl.UseRoles({
    resource: "PaymentLink",
    action: "update",
    possession: "any",
  })
  async disconnectTransactions(
    @common.Param() params: PaymentLinkWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updatePaymentLink({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/paymentLink/:id/status")
  @swagger.ApiOkResponse({
    type: PaymentLink,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetPaymentLinkStatus(
    @common.Body()
    body: PaymentLinkWhereUniqueInput
  ): Promise<PaymentLink> {
    return this.service.GetPaymentLinkStatus(body);
  }
}
